### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function getColumn() on null

### ISSUE THREAD

**Issue by sojohnnysaid** [X2Engine/X2CRM#155]
This is my output after installation. I was told I needed ssh2, installed it, the message went away. Database was tested all good.

This was on the page when clicking the link to login

Notice: unserialize(): Unexpected end of serialized data in /home/forge/crm.localtech.shop/public/framework/caching/CCache.php on line 108

Notice: unserialize(): Error at offset 0 of 1 bytes in /home/forge/crm.localtech.shop/public/framework/caching/CCache.php on line 108

Notice: unserialize(): Unexpected end of serialized data in /home/forge/crm.localtech.shop/public/framework/caching/CCache.php on line 108

Notice: unserialize(): Error at offset 0 of 1 bytes in /home/forge/crm.localtech.shop/public/framework/caching/CCache.php on line 108

Notice: unserialize(): Unexpected end of serialized data in /home/forge/crm.localtech.shop/public/framework/caching/CCache.php on line 108

Notice: unserialize(): Error at offset 0 of 1 bytes in /home/forge/crm.localtech.shop/public/framework/caching/CCache.php on line 108

Notice: Trying to get property of non-object in /home/forge/crm.localtech.shop/public/framework/db/ar/CActiveRecord.php on line 661

Fatal error: Uncaught Error: Call to a member function getColumn() on null in /home/forge/crm.localtech.shop/public/framework/db/schema/CDbCommandBuilder.php:675 Stack trace: #0 /home/forge/crm.localtech.shop/public/framework/db/ar/CActiveRecord.php(1540): CDbCommandBuilder->createColumnCriteria(NULL, Array, '', Array, '`t`.') #1 /home/forge/crm.localtech.shop/public/protected/models/X2Model.php(442): CActiveRecord->findAllByAttributes(Array) #2 /home/forge/crm.localtech.shop/public/protected/models/X2Model.php(381): X2Model::getModules() #3 /home/forge/crm.localtech.shop/public/protected/components/behaviors/QuickCreateRelationshipBehavior.php(69): X2Model::getModelNames() #4 /home/forge/crm.localtech.shop/public/protected/components/X2ClientScript.php(847): QuickCreateRelationshipBehavior::getModelsWhichSupportQuickCreate(true) #5 /home/forge/crm.localtech.shop/public/protected/components/X2ClientScript.php(1104): X2ClientScript->registerX2QuickCRUD() #6 /home/forge/crm.localtech.shop/public/protected/views/layouts/main in /home/forge/crm.localtech.shop/public/framework/db/schema/CDbCommandBuilder.php on line 675

**Comment by asadali3210** [comment]
Apparently, it looks like an issue with the database columns. 

> This was on the page when clicking the link to login

@sojohnnysaid Did you click on the Login link after the installation completed? 
Or, from somewhere else?

**Comment by sojohnnysaid** [comment]
@asadali3210 Just followed the prompt to continue on the page after completing the installation. Let me know if you need any more info (os version any package versions on my system). Would really like to work with your awesome product!
